# Generated by Django 5.1.1 on 2024-09-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='password',
            field=models.CharField(max_length=128, null=True, verbose_name='password'),
        ),
    ]
