# Generated by Django 5.1.1 on 2024-09-18 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 18, 16, 4, 42, 720290, tzinfo=datetime.timezone.utc)),
        ),
    ]
